#!/bin/bash
echo Release: test_tag
echo Tag: test_tag
echo Latest Commit Hash: 4e85bef5b05d748e976bbf99159f05efdc1e95af
echo Latest Commit Date: 2025-03-28 22:09:01 +0000
echo Github Branch Version: 2.11.1_stackversion
