apiVersion: 1
groups:
    - orgId: 1
      name: Errors requiring reboot and may be repair
      folder: Critical
      interval: 5m
      rules:
        - uid: xid-error
          title: XID Error Check
          condition: A
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: Prometheus
              model:
                editorMode: code
                expr: xid_error_check==0
                instant: true
                intervalMs: 1000
                legendFormat: '{{hostname}}'
                maxDataPoints: 43200
                range: false
                refId: A
          dashboardUid: ""
          panelId: 0
          noDataState: NoData
          execErrState: OK
          for: 5m
          annotations:
            summary: XID error check has failed. The XID error check value is 0, indicating a potential issue with the system’s transaction or GPU hardware error on {{hostname}}. Immediate investigation is required.
          labels: {}
          isPaused: false
          notification_settings:
            receiver: grafana-default-email
        - uid: ecc-error
          title: GPU ECC Error Check
          condition: A
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: Prometheus
              model:
                editorMode: code
                expr: gpu_ecc_error_check == 0
                instant: true
                intervalMs: 1000
                legendFormat: '{{hostname}}'
                maxDataPoints: 43200
                range: false
                refId: A
          dashboardUid: ""
          panelId: 0
          noDataState: NoData
          execErrState: OK
          for: 5m
          annotations:
            summary: GPU ECC error check has failed. The ECC error check value is 0, indicating a potential memory issue with the GPU on {{hostname}}. Immediate investigation is required, and a node reboot may be necessary if the issue persists.
          labels: {}
          isPaused: false
          notification_settings:
            receiver: grafana-default-email
        - uid: row-remap-error
          title: GPU Row Remap Error Check
          condition: A
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: Prometheus
              model:
                editorMode: code
                expr: gpu_row_remap_error_check == 1
                instant: true
                intervalMs: 1000
                legendFormat: '{{hostname}}'
                maxDataPoints: 43200
                range: false
                refId: A
          dashboardUid: ""
          panelId: 0
          noDataState: NoData
          execErrState: OK
          for: 5m
          annotations:
            summary: GPU row remap error check has failed. The row remap error check value is 1, indicating a potential issue with GPU memory that may require a reboot on {{hostname}}. Immediate investigation is recommended.
          labels: {}
          isPaused: false
          notification_settings:
            receiver: grafana-default-email
    - orgId: 1
      name: Events that might cause cluster instability
      folder: Critical
      interval: 1m
      rules:
        - uid: disk-20pct
          title: Controller or Login nodes should have disk free more than 20pct
          condition: A
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: Prometheus
              model:
                editorMode: code
                expr: ((node_filesystem_avail_bytes{mountpoint="/", hostname=~".*controller|.*login"} / node_filesystem_size_bytes{mountpoint="/", hostname=~".*controller|.*login"})*100) < 20
                instant: true
                intervalMs: 1000
                legendFormat: '{{hostname}}'
                maxDataPoints: 43200
                range: false
                refId: A
          noDataState: NoData
          execErrState: OK
          for: 1m
          annotations: {}
          labels: {}
          isPaused: false
          notification_settings:
            receiver: grafana-default-email
        - uid: mem-20pct
          title: Controller or Login nodes should have memory free more than 20pct
          condition: A
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: Prometheus
              model:
                editorMode: code
                expr: (100 * ((node_memory_MemAvailable_bytes{hostname=~".*controller|.*login"}) / (node_memory_MemTotal_bytes{hostname=~".*controller|.*login"}))) < 20
                instant: true
                intervalMs: 1000
                legendFormat: '{{hostname}}'
                maxDataPoints: 43200
                range: false
                refId: A
          noDataState: NoData
          execErrState: OK
          for: 1m
          annotations: {}
          labels: {}
          isPaused: false
          notification_settings:
            receiver: grafana-default-email
        - uid: cpu-20pct
          title: Controller or Login nodes should not have cpu usage more than 90%
          condition: A
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: Prometheus
              model:
                editorMode: code
                expr: ((avg by (instance) (irate(node_cpu_seconds_total{mode="idle", hostname=~".*controller|.*login"}[5m])) * 100)) < 20
                instant: true
                intervalMs: 1000
                legendFormat: '{{hostname}}'
                maxDataPoints: 43200
                range: false
                refId: A
          noDataState: NoData
          execErrState: OK
          for: 1m
          annotations: {}
          labels: {}
          isPaused: false
          notification_settings:
            receiver: grafana-default-email
    - orgId: 1
      name: GPU throttling or shutdown due to different power and temperature violations
      folder: Critical
      interval: 1m
      rules:
        - uid: throttle-power
          title: GPU throttle due to power violation
          condition: A
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: Prometheus
              model:
                editorMode: code
                expr: (DCGM_FI_DEV_POWER_VIOLATION) > 0
                instant: true
                intervalMs: 1000
                legendFormat: '{{hostname}} {{device}}'
                maxDataPoints: 43200
                range: false
                refId: A
          noDataState: NoData
          execErrState: OK
          for: 1m
          annotations: {}
          labels: {}
          isPaused: false
          notification_settings:
            receiver: grafana-default-email
        - uid: throttle-board
          title: GPU throttle due to board limit violation
          condition: A
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: Prometheus
              model:
                editorMode: code
                expr: (DCGM_FI_DEV_BOARD_LIMIT_VIOLATION) > 0
                instant: true
                intervalMs: 1000
                legendFormat: '{{hostname}} {{device}}'
                maxDataPoints: 43200
                range: false
                refId: A
          noDataState: NoData
          execErrState: OK
          for: 1m
          annotations: {}
          labels: {}
          isPaused: false
          notification_settings:
            receiver: grafana-default-email          
        - uid: throttle-thermal
          title: GPU throttle due to thermal violation
          condition: A
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: Prometheus
              model:
                editorMode: code
                expr: (DCGM_FI_DEV_THERMAL_VIOLATION) > 0
                instant: true
                intervalMs: 1000
                legendFormat: '{{hostname}} {{device}}'
                maxDataPoints: 43200
                range: false
                refId: A
          noDataState: NoData
          execErrState: OK
          for: 1m
          annotations: {}
          labels: {}
          isPaused: false
          notification_settings:
            receiver: grafana-default-email   
        - uid: throttle-util
          title: GPU throttle due to low utilization violation
          condition: A
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: Prometheus
              model:
                editorMode: code
                expr: (DCGM_FI_DEV_LOW_UTIL_VIOLATION) > 0
                instant: true
                intervalMs: 1000
                legendFormat: '{{hostname}} {{device}}'
                maxDataPoints: 43200
                range: false
                refId: A
          noDataState: NoData
          execErrState: OK
          for: 1m
          annotations: {}
          labels: {}
          isPaused: false
          notification_settings:
            receiver: grafana-default-email  
        - uid: throttle-sync
          title: GPU throttle due to sync boost violation
          condition: A
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: Prometheus
              model:
                editorMode: code
                expr: (DCGM_FI_DEV_SYNC_BOOST_VIOLATION) > 0
                instant: true
                intervalMs: 1000
                legendFormat: '{{hostname}} {{device}}'
                maxDataPoints: 43200
                range: false
                refId: A
          noDataState: NoData
          execErrState: OK
          for: 1m
          annotations: {}
          labels: {}
          isPaused: false
          notification_settings:
            receiver: grafana-default-email  
        - uid: throttle-reliability
          title: GPU throttle due to reliability violation
          condition: A
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: Prometheus
              model:
                editorMode: code
                expr: (DCGM_FI_DEV_RELIABILITY_VIOLATION) > 0
                instant: true
                intervalMs: 1000
                legendFormat: '{{hostname}} {{device}}'
                maxDataPoints: 43200
                range: false
                refId: A
          noDataState: NoData
          execErrState: OK
          for: 1m
          annotations: {}
          labels: {}
          isPaused: false
          notification_settings:
            receiver: grafana-default-email 
        - uid: gpu-temp-slowdown
          title: GPU device memory temperature exceeded 90% of slowdown temparature
          condition: A
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: Prometheus
              model:
                editorMode: code
                expr: (DCGM_FI_DEV_MEMORY_TEMP / DCGM_FI_DEV_SLOWDOWN_TEMP) > 0.9
                instant: true
                intervalMs: 1000
                legendFormat: '{{hostname}} {{device}}'
                maxDataPoints: 43200
                range: false
                refId: A
          noDataState: NoData
          execErrState: OK
          for: 1m
          annotations: {}
          labels: {}
          isPaused: false
          notification_settings:
            receiver: grafana-default-email 
        - uid: gpu-temp-shutdown
          title: GPU device temperature exceeded 90% of shutdown temperature
          condition: A
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: Prometheus
              model:
                editorMode: code
                expr: (DCGM_FI_DEV_GPU_TEMP / DCGM_FI_DEV_SHUTDOWN_TEMP) > 0.9
                instant: true
                intervalMs: 1000
                legendFormat: '{{hostname}} {{device}}'
                maxDataPoints: 43200
                range: false
                refId: A
          noDataState: NoData
          execErrState: OK
          for: 1m
          annotations: {}
          labels: {}
          isPaused: false
          notification_settings:
            receiver: grafana-default-email 
        - uid: mem-temp-slowdown
          title: GPU device memory temperature exceeded 90% of slowdown temperature
          condition: A
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: Prometheus
              model:
                editorMode: code
                expr: (DCGM_FI_DEV_MEMORY_TEMP / DCGM_FI_DEV_SLOWDOWN_TEMP) > 0.9
                instant: true
                intervalMs: 1000
                legendFormat: '{{hostname}} {{device}}'
                maxDataPoints: 43200
                range: false
                refId: A
          noDataState: NoData
          execErrState: OK
          for: 1m
          annotations: {}
          labels: {}
          isPaused: false
          notification_settings:
            receiver: grafana-default-email 
        - uid: mem-temp-shutdown
          title: GPU device memory temperature exceeded 90% of shutdown temperature
          condition: A
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: Prometheus
              model:
                editorMode: code
                expr: (DCGM_FI_DEV_MEMORY_TEMP / DCGM_FI_DEV_SHUTDOWN_TEMP) > 0.9
                instant: true
                intervalMs: 1000
                legendFormat: '{{hostname}} {{device}}'
                maxDataPoints: 43200
                range: false
                refId: A
          noDataState: NoData
          execErrState: OK
          for: 1m
          annotations: {}
          labels: {}
          isPaused: false
          notification_settings:
            receiver: grafana-default-email 
    - orgId: 1
      name: Errors if occurring over longer periods that might require repair
      folder: Critical
      interval: 5m
      rules:
        - uid: rdma-device-status
          title: RDMA Device Status
          condition: A
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: Prometheus
              model:
                editorMode: code
                expr: rdma_device_status == 0
                instant: true
                intervalMs: 1000
                legendFormat: '{{hostname}}'
                maxDataPoints: 43200
                range: false
                refId: A
          dashboardUid: ""
          panelId: 0
          noDataState: NoData
          execErrState: OK
          for: 5m
          annotations:
            summary: RDMA device status check has failed. The RDMA device status value is 0, indicating a potential issue with the RDMA hardware on {{hostname}}. Immediate investigation is required, and a node reboot may be necessary if the issue persists.
          labels: {}
          isPaused: false
          notification_settings:
            receiver: grafana-default-email
        - uid: rdma-link-flap
          title: RDMA Link Flapping
          condition: A
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: Prometheus
              model:
                editorMode: code
                expr: rdma_link_noflap == 0
                instant: true
                intervalMs: 1000
                legendFormat: '{{hostname}}'
                maxDataPoints: 43200
                range: false
                refId: A
          dashboardUid: ""
          panelId: 0
          noDataState: NoData
          execErrState: OK
          for: 5m
          annotations:
            summary: RDMA link status check has failed. The RDMA link no flap value is 0, indicating potential instability in the RDMA link on {{hostname}}. Immediate investigation is required.
          labels: {}
          isPaused: false
          notification_settings:
            receiver: grafana-default-email
        - uid: rttcc-status
          title: RTTCC Status
          condition: A
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: Prometheus
              model:
                editorMode: code
                expr: rttcc_status == 1
                instant: true
                intervalMs: 1000
                legendFormat: '{{hostname}}'
                maxDataPoints: 43200
                range: false
                refId: A
          dashboardUid: ""
          panelId: 0
          noDataState: NoData
          execErrState: OK
          for: 5m
          annotations:
            summary: RTTCC status check has failed. RTTCC should always be disabled, indicating potential issues with congestion control on {{hostname}}. Immediate investigation is required.
          labels: {}
          isPaused: false
          notification_settings:
            receiver: grafana-default-email
